src/app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.HomeView.as_view(), name='home'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('solicitudes/<pk>/', views.UserDetailView.as_view(), name='user-detail'),
    path('aprobado/<pk>/', views.AprobarView.as_view(), name='aprobado'),
    path('rechazado/<pk>/', views.RechazarView.as_view(), name='rechazado')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/core/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.deletion import CASCADE
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.
User = get_user_model()

class DeudaSbs(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    monto_deuda = models.IntegerField(default=0)

    def __str__(self) -> str:
        return str(self.monto_deuda)

    def get_sbs_status(self):
        return "{:.2f}".format(self.monto_deuda / 100)

class Solicitud(models.Model):
    SENTINEL_CHOICES = (
        ('B', 'Bueno'),
        ('R', 'Regular'),
        ('M', 'Malo')
    )
    STATUS_CHOICES = (
        ('E', 'En Proceso'),
        ('A', 'Aprovado'),
        ('N', 'No Aprovado')
    )
    user = models.ForeignKey(User, on_delete=CASCADE)
    fecha = models.DateField(auto_now_add=False)
    estado = models.CharField(max_length=1 ,choices=STATUS_CHOICES)
    monto = models.IntegerField(default=0)
    actualizado = models.DateTimeField(auto_now=True)
    sbs_status = models.ForeignKey(DeudaSbs, on_delete=models.CASCADE)
    ia_algoritm = models.IntegerField(default=1, validators=[MaxValueValidator(10), MinValueValidator(1)])
    sentinel_status = models.CharField(max_length=1, choices=SENTINEL_CHOICES)

    def __str__(self) -> str:
        return self.refernce_number

    def get_monto(self):
        return "{:.2f}".format(self.monto / 100)

    @property 
    def refernce_number(self):
        return f"SOLICITUD-{self.pk}"

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Django Credit{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock extra_head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'icons/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'icons/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'icons/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'icons/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'icons/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'icons/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'icons/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'icons/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'icons/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'icons/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'icons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'icons/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'icons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'icons/manifest.json' %}">

    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'icons/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css"
          integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous"/>
</head>

<body>

<div class="site-wrap">
    <header class="site-navbar" role="banner">
        <div class="site-navbar-top">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-6 col-md-8 mb-3 mb-md-0 col-md-4 order-1 order-md-2">
                        <div>
                            <a href="{% url 'home' %}">
                                <img class="img-fluid" src="{% static 'images/logo2.png' %}" style="max-width: 150px;"/>
                            </a>
                        </div>
                    </div>

                    <div class="col-6 col-md-4 order-3 order-md-3 text-right">
                        <div class="site-top-icons">
                            <ul>
                                <li>
                                    {% if request.user.is_authenticated %}
                                        <a href="{% url 'profile' %}"><span><i class="fas fa-user"></i></span></a>
                                    {% else %}
                                        <a href="{% url 'account_login' %}"><span><i
                                                class="fas fa-sign-in-alt"></i></span></a>
                                    {% endif %}
                                </li>
                                <li class="d-inline-block d-md-none ml-md-0">
                                    <a href="#" class="site-menu-toggle js-menu-toggle">
                                        <span><i class="fas fa-bars"></i></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        {% include 'navbar.html' %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    <span class="alert-inner--icon"><i class="ni ni-like-2"></i></span>
                    <span class="alert-inner--text">{{ message }}</span>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        {% endif %}

    </header>

    {% block content %}
    {% endblock content %}

    {% include 'footer.html' %}

</div>

{% include 'scripts.html' %}

{% block scripts %}
{% endblock scripts %}

</body>
</html>

src/templates/footer.html
<footer class="site-footer border-top">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <p>
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This website is made with <i class="fas fa-heart"></i>
                </p>
            </div>
        </div>
    </div>
</footer>

src/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="site-blocks-cover" style="background-image: url({% static 'images/hero2.jpg' %});" data-aos="fade">
    <div class="container">
        <div class="row">
            <div class="col-md-4 pt-5 pt-md-0">

            </div>
        </div>
    </div>
</div>

{% endblock content %}

src/templates/navbar.html
<nav class="site-navigation text-right text-md-center" role="navigation">
    <div class="container">
        <ul class="site-menu js-clone-nav d-none d-md-block" style="padding: 0;">
            <li><a href="/">Home</a></li>
            {% if request.user.is_staff %}
                <li><a href="{% url 'profile' %}">Solicitudes</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

src/templates/profile.html
{% extends "base.html" %} {% block content %}
<div class="site-sectino">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-m-12">
        <h2 class="text-black">Tu Perfil</h2>
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{ request.user.email }}</h5>
            <a href="{% url 'account_logout' %}"
              ><small class="float-right">Logout</small></a
            >
          </div>
          <hr />
          <h5 class="card-title">Tus Solicitudes</h5>
          <div class="site-blocks-table">
            <table class="table">
              <thead>
                <tr>
                  <th>No. Referencia</th>
                  <th>Usuario</th>
                  <th>Fecha</th>
                  <th>Monto</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {% for solicitud in solicitudes %}
                <tr>
                  <td>#{{ solicitud.pk }} </td>
                  <td><a href="{% url 'user-detail' solicitud.pk %}">{{ solicitud.user }}</a></td>
                  <td>{{ solicitud.fecha }}</td>
                  <td>${{ solicitud.get_monto }}</td>
                  <td>{{ solicitud.get_estado_display }}</td>
                </tr>
                {% empty %}
                <tr>
                  <td colspan="4">You havent made any purchases</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

src/templates/scripts.html
{% load static %}

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

src/templates/solicitud.html
{% extends "base.html" %} {% block content %}

<div class="site-sectino">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-m-12">
        <h2 class="text-black">Solicitud #{{ solicitud.pk }}</h2>
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{ request.user.email }}</h5>
            <a href="{% url 'account_logout' %}"
              ><small class="float-right">Logout</small></a
            >
          </div>
          <hr />
          <div class="site-blocks-table">
            <div>
              <h4>
                Puntaje del algoritmo {{ solicitud.ia_algoritm }}
              </h4>
            </div>
            <div class="progress">
              <div class="progress-bar" role="progressbar" style="width: 50%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            <table class="table">
              <thead>
                <tr>
                  <th>No. Referencia</th>
                  <th>Usuario</th>
                  <th>Fecha</th>
                  <th>Monto</th>
                  <th>Deuda SBS</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>#{{ solicitud.pk }} </td>
                  <td><a href="#">{{ solicitud.user }}</a></td>
                  <td>{{ solicitud.fecha }}</td>
                  <td>${{ solicitud.get_monto }}</td>
                  <td>${{ solicitud.sbs_status.get_sbs_status }}</td>
                  <td>{{ solicitud.get_estado_display }}</td>
                </tr>
              </tbody>
            </table>
            <div>
              {% if solicitud.estado == "E" %}
                <div>
                  <a href="{% url 'aprobado' solicitud.id %}" class="btn btn-primary mb-3">Aprobar</a>
                  <a href="{% url 'rechazado' solicitud.id %}" class="btn btn-danger mb-3">Rechazar</a>
                </div>
                <div>
                  
                </div>
              {% endif %}
              
            </div>
            
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}